### PR TITLE
Tons of improvements

### PR DESCRIPTION
**Pull request by r3pwn**
+ Lets it compile once again
+ Lets us have our own vendor repo
+ Removes all of the sony-specific binaries and libraries
+ Allows models to be more easily recognizable in the Settings app

The only caveat is that after this pull request is accepted and merged, everyone will need to either pull their own blobs for the vendor repo, or clone them from https://github.com/r3pwn/proprietary_vendor_nokia
(I would recommend forking this repo to Android4Lumia to make this process easier for everyone)

### CODE REVIEW

**Comment by r3pwn** [comment]
I just realized, this also fixes the correction that the author from #4 had suggested.

**Comment by sjrmac** [comment]
I'll let Feherneoh decide on this one as we have plans to make ourselves independent from the Sony stuff like you suggest here. He might want to do this a different way as we have other plans on how we want to do trees.

**Comment by r3pwn** [comment]
Alright, sounds good. If you end up deciding against accepting it, I would feel that much of the content here would go to waste, so feel free to let me know which commits you want to keep (if any) and I'll be more than happy to throw them into a separate PR for you.

**Comment by sjrmac** [comment]
I personally like the changes you have made, do you have a build with these changes so I can look at a few things? email is sjrmac@gmail.com

**Comment by r3pwn** [comment]
I haven't built in a while, but I do have a build that includes all of these changes. I might be able to get the build for you in a bit. It was on my desktop, and I just finished moving, haven't set up my desktop yet. I may just build on my laptop for the time being, test the build out, then send it over.
Most of the changes I made were just to get it to compile. I can't remember if audio works or not, but I know that everything that was broken previously is still broken.

**Comment by sjrmac** [comment]
Yeah, we are working on a updated boot loader and wifi, then my 920 in our free time

**Comment by feherneoh** [comment]
@sjrmac you can merge this if you want to, as this goes to the cm-14.1 branch
I'll recreate it anyways (using the useful patches merged there) after I consider cm-13.0 to be stable

**Comment by ghost** [comment]
Short question about @r3pwn 's kernel tree: Is it normal that it bootloops?

**Comment by r3pwn** [comment]
Nope. You using the right kernel config and everything? Have you run a repo sync recently?

**Comment by ghost** [comment]
Yes.

**Comment by r3pwn** [comment]
Then I recommend you make clobber, pull the device blobs, then do a clean build, because it works.

**Comment by ghost** [comment]
Do I have to set sepolicy to permissive to make it boot?

**Comment by r3pwn** [comment]
If you merged all of these changes, then that should be done already. It's a good idea to set it to permissive for development purposes then set it to enforcing after you fix everything.

**Comment by ghost** [comment]
Still not working...

**Comment by feherneoh** [comment]
feel free to mess anything with cm-14.1, but I personally won't merge anything to that branch, as the whole thing will be recreated from 0 later. If the pull request, and branches from others stay, I'll be able to merge everything I want in after the rewrite

**Pull request closed without merging**
