### PR TITLE
Better bootup logo

### PR DESCRIPTION
**Pull request by ghost**
with Android 5.0+ logo in green.

### CODE REVIEW

**Comment by sjrmac** [comment]
first we will see how the other one looks, but I want to make another one eventually. ill keep it open for now

**Comment by alula** [comment]
make android bigger and while.
and to build the initlogo.rle:
1. Save as RGB565 RAW file.
2. `to565 -rle < initlogo.raw > initlogo.rle`
3. Place initlogo.rle in ramdisk root and rebuild it.
4. Flash the ramdisk to phone.

**Comment by feherneoh** [comment]
The white one is simpler, looks better. Brand + OS, nothing more.

**Comment by ghost** [comment]
I have only found this new logo in green and edited it with MS Paint.

**Comment by ghost** [comment]
Can I save png as RGB565 RAW file with this ImageMagick
"convert -depth 8 -size 480x800 initlogo.png rgb:initlogo.raw" command?

**Comment by ghost** [comment]
Oops... Little accident. I closed this. But I will reopen again.

**Pull request closed without merging**
