### PR TITLE
Another performance patch

### PR DESCRIPTION
**Pull request by ghost**
Change the LineageOS configuration from full to mini, already done this on my builds. That's why on my builds there is no LineageOS recorder.

### CODE REVIEW

**Comment by feherneoh** [comment]
Can you tell me what the differences are? I'm too lazy to check the makefiles myself.

**Comment by ghost** [comment]
Close this PR, this is useless and will be reverted in my builds.

**Comment by feherneoh** [comment]
Why exactly is this useless? I was just about to pull this into my downstream branch

**Comment by ghost** [comment]
@feherneoh It makes no useful diffrence. Some dictionaries for the keyboard and the combined Screen and Sound recorder would be missing.
Short question at the end: Does the the new NV bin makes Wi-Fi working?

**Comment by feherneoh** [comment]
@trashmaster76 
Do we need any of those features on these phones? We want the ROM to work, not to be the same as on like 1+5. We can throw anything out that does not make the phone unusable, and dictionaries, screen recording and stuff like that falls into that category.
No, adding the NV does not help, but we need some placeholders so the makefiles won't have to be edited (and cleaned up again by me) when we fix stuff. We have the accelerometer driver and its full config added the same way, even though that doesn't work yet.

**Comment by feherneoh** [comment]
Just checked the makefiles, they really won't help with RAM problems, they are mostly for devices with tiny /system partitions.

**Pull request closed without merging**
